# Generated by Django 5.2 on 2025-04-07 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
        ('problems', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('points', models.IntegerField(default=100)),
                ('order', models.PositiveIntegerField()),
                (
                    'contest',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contests.contest',
                    ),
                ),
                (
                    'problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='problems.problem',
                    ),
                ),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestSolution',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('solved_time', models.DateTimeField(auto_now_add=True)),
                ('penalty', models.IntegerField(default=0)),
                (
                    'contest_problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contests.contestproblem',
                    ),
                ),
                (
                    'submission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='submissions.submission',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['solved_time'],
                'unique_together': {('user', 'contest_problem')},
            },
        ),
        migrations.AddField(
            model_name='contestproblem',
            name='solved_by',
            field=models.ManyToManyField(
                blank=True,
                through='contests.ContestSolution',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name='ContestRegistration',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True)),
                (
                    'contest',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contests.contest',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'unique_together': {('user', 'contest')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('contest', 'problem')},
        ),
    ]
