# Generated by Django 5.2 on 2025-04-07 19:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestproblem_contestsolution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(
                blank=True,
                related_name='contests_participated',
                through='contests.ContestRegistration',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
