# Generated by Django 5.2 on 2025-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contestproblem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestsolution',
            name='penalty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='contestsolution',
            name='solved_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
