# Generated by Django 5.2 on 2025-04-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_alter_contestsolution_penalty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestproblem',
            name='solved_by',
        ),
        migrations.DeleteModel(
            name='ContestSolution',
        ),
    ]
