# Generated by Django 5.2 on 2025-04-07 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=20)),
                (
                    'verdict',
                    models.CharField(
                        choices=[
                            ('AC', 'Accepted'),
                            ('WA', 'Wrong Answer'),
                            ('TLE', 'Time Limit Exceeded'),
                            ('MLE', 'Memory Limit Exceeded'),
                            ('RE', 'Runtime Error'),
                            ('CE', 'Compilation Error'),
                        ],
                        default='QU',
                        max_length=3,
                    ),
                ),
                ('time_taken', models.FloatField(blank=True, null=True)),
                ('memory_used', models.FloatField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                (
                    'problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='problems.problem',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
