# Generated by Django 5.2 on 2025-04-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_tag_alter_problem_options_alter_testcase_options_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='test_error',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='problems.testcase',
            ),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(
                choices=[
                    ('AC', 'Accept'),
                    ('CE', 'Compilation error'),
                    ('WA', 'Wrong answer'),
                    ('TL', 'Time limit'),
                    ('RE', 'Runtime error'),
                    ('ML', 'Memory limit'),
                    ('IQ', 'In queue'),
                    ('IP', 'In processing'),
                ],
                default='IQ',
                max_length=3,
            ),
        ),
    ]
