# Generated by Django 5.2 on 2025-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_test_error_alter_submission_verdict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='memory_used',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='submission',
            name='logs',
            field=models.TextField(blank=True, verbose_name='logs'),
        ),
    ]
