# Generated by Django 5.2 on 2025-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_submission_memory_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='logs'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='verdict',
            field=models.CharField(
                choices=[
                    ('AC', 'Accept'),
                    ('CE', 'Compilation error'),
                    ('WA', 'Wrong answer'),
                    ('TL', 'Time limit'),
                    ('RE', 'Runtime error'),
                    ('ML', 'Memory limit'),
                    ('IQ', 'In queue'),
                    ('IP', 'In processing'),
                ],
                default='IQ',
            ),
        ),
    ]
