# Generated by Django 5.2b1 on 2025-03-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профили",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="coffee_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество кофе"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_images/",
                verbose_name="аватарка",
            ),
        ),
    ]
