# Generated by Django 5.2 on 2025-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coffee_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0, verbose_name='количество очков'),
        ),
    ]
