# Generated by Django 5.2 on 2025-04-06 09:19

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '__first__'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'solution', 'verbose_name_plural': 'solutions'},
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='author',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='input_format',
            field=tinymce.models.HTMLField(
                default=None,
                help_text='Input data format',
                max_length=1000,
                verbose_name='input data format',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='output_format',
            field=tinymce.models.HTMLField(
                default='',
                help_text='Output data format',
                max_length=1000,
                verbose_name='output data format',
            ),
            preserve_default=False,
        ),
    ]
