# Generated by Django 5.2 on 2025-04-06 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_solution_options_alter_task_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.TextField(max_length=8000, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='lang',
            field=models.TextField(
                choices=[('Py3.11', 'Python 3.11')], verbose_name='programming language'
            ),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='solutions',
                to='tasks.task',
                verbose_name='task',
            ),
        ),
        migrations.AlterField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='solutions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='author',
            ),
        ),
    ]
