# Generated by Django 5.2b1 on 2025-04-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_profile_birthday_remove_profile_coffee_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        choices=[('python', 'Python'), ('c++', 'C++')],
                        default='python',
                        max_length=50,
                    ),
                ),
                ('ace_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CodeRoom',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='owned_rooms',
                        to='users.user',
                    ),
                ),
                (
                    'participants',
                    models.ManyToManyField(related_name='code_rooms', to='users.user'),
                ),
                (
                    'language',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='duet.programminglanguage',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='RoomInvitation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=False)),
                (
                    'invitee',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='received_invites',
                        to='users.user',
                    ),
                ),
                (
                    'inviter',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sent_invites',
                        to='users.user',
                    ),
                ),
                (
                    'room',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='duet.coderoom'
                    ),
                ),
            ],
            options={
                'unique_together': {('room', 'invitee')},
            },
        ),
    ]
