# Generated by Django 5.2b1 on 2025-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet', '0001_initial'),
        ('users', '0004_remove_profile_birthday_remove_profile_coffee_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderoom',
            name='participants',
            field=models.ManyToManyField(
                related_name='participating_rooms', to='users.user'
            ),
        ),
    ]
