# Generated by Django 5.2b1 on 2025-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duet', '0002_alter_coderoom_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(default='python', max_length=50),
        ),
    ]
