# Generated by Django 5.2 on 2025-04-07 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                (
                    'difficulty',
                    models.CharField(
                        choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')],
                        max_length=1,
                    ),
                ),
                ('time_limit', models.IntegerField(default=1)),
                ('memory_limit', models.IntegerField(default=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False)),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'input_field',
                    models.TextField(db_column='input', verbose_name='input'),
                ),
                ('output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                (
                    'problem',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='problems.problem',
                    ),
                ),
            ],
        ),
    ]
