# Generated by Django 5.2 on 2025-04-09 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_tag_alter_problem_options_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(
                default=256,
                validators=[
                    django.core.validators.MaxValueValidator(512),
                    django.core.validators.MinValueValidator(64),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(5),
                    django.core.validators.MinValueValidator(1),
                ],
            ),
        ),
    ]
