# Generated by Django 5.2 on 2025-04-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_tag_alter_problem_options_alter_testcase_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='auther_language',
            new_name='author_language',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='auther_solution',
            new_name='author_solution',
        ),
    ]
