# Generated by Django 5.2 on 2025-04-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_testcase_number_alter_testcase_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={
                'ordering': ['number'],
                'verbose_name': 'test case',
                'verbose_name_plural': 'tests cases',
            },
        ),
        migrations.AlterField(
            model_name='testcase',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='number of test'),
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='auther_language',
            new_name='author_language',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='auther_solution',
            new_name='author_solution',
        ),
    ]
