# Generated by Django 5.2 on 2025-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_author_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(
                related_name='tasks', to='problems.tag', verbose_name='tags'
            ),
        ),
    ]
