# Generated by Django 5.2 on 2025-04-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_alter_problem_tags'),
        ('problems', '0005_alter_testcase_options_alter_testcase_number_and_more'),
    ]

    operations = []
