# Generated by Django 5.2 on 2025-04-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_merge_20250412_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(
                blank=True, related_name='tasks', to='problems.tag', verbose_name='tags'
            ),
        ),
    ]
