# Generated by Django 5.2 on 2025-04-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_alter_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(
                help_text='Input data for the test. It will be passed to the program during execution via the standard stream',
                verbose_name='input data',
            ),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_data',
            field=models.TextField(
                help_text='Test output. The program should output exactly this text in this format',
                verbose_name='output data',
            ),
        ),
    ]
