# Generated by Django 5.2 on 2025-04-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0008_alter_testcase_input_data_alter_testcase_output_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_correct',
            field=models.BooleanField(
                default=False,
                help_text="Shows whether the author's solution is correct",
                verbose_name='is correct',
            ),
        ),
        migrations.AddField(
            model_name='problem',
            name='logs',
            field=models.TextField(blank=True, verbose_name='logs'),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(
                choices=[
                    ('AC', 'Accept'),
                    ('CE', 'Compilation error'),
                    ('WA', 'Wrong answer'),
                    ('TL', 'Time limit'),
                    ('RE', 'Runtime error'),
                    ('ML', 'Memory limit'),
                    ('IQ', 'In queue'),
                    ('IP', 'In processing'),
                ],
                default='IQ',
            ),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_error',
            field=models.IntegerField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
