# Generated by Django 5.2 on 2025-04-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_problem_is_correct_problem_logs_problem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='logs',
            field=models.TextField(blank=True, null=True, verbose_name='logs'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_error',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
