# Generated by Django 5.2 on 2025-04-20 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_alter_problem_logs_alter_problem_test_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(
                choices=[
                    ('AC', 'Accept'),
                    ('CE', 'Compilation error'),
                    ('WA', 'Wrong answer'),
                    ('TL', 'Time limit'),
                    ('RE', 'Runtime error'),
                    ('ML', 'Memory limit'),
                    ('IQ', 'In queue'),
                    ('IP', 'In processing'),
                ],
                default='IQ',
                verbose_name='status checked',
            ),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_error',
            field=models.IntegerField(blank=True, null=True, verbose_name='test error'),
        ),
    ]
